version: "3.8"
services:
  db:
    image: mysql:8.0.33
    container_name: test-cicd-mysql
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: user-docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: test-cicd
    ports:
      - "3306:3306"
    networks:
      - test-cicd-network

  api-customer-registration:
    image: augustomarques/test-cicd
    container_name: test-cicd-app
    build: .
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user-docker
      DB_PASSWORD: docker
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    networks:
      - test-cicd-network

networks:
  test-cicd-network:
    driver: bridge
